name: Build and Deploy Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📂 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🏗️ Build for production
      run: |
        # Build with current .env configuration
        npm run build
      
    - name: 📋 Build Complete
      run: |
        echo "🎉 Build completed successfully!"
        echo "📁 Contents of dist folder:"
        ls -la dist/
        echo "📊 Build size:"
        du -sh dist/
        echo ""
        echo "📋 Ready for deployment!"
        echo "🌐 Frontend: https://crm.gandhibaideaddictioncenter.com" 
        echo "🔗 Backend: https://gandhi-bai.onrender.com/api"
        echo ""
        echo "💡 Next steps:"
        echo "1. Download the 'dist' folder from GitHub Actions artifacts"
        echo "2. Upload contents to your hosting provider's public_html folder"
        echo "3. Your CRM will be live!"

    - name: 📦 Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: dist/
        retention-days: 30
